# Generated by Django 4.0.2 on 2022-02-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mydrinks',
            field=models.CharField(max_length=100),
        ),
    ]
