# Generated by Django 4.0.2 on 2022-02-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('ice', models.CharField(default='no ice', max_length=100)),
                ('spirit', models.CharField(default='no spirit', max_length=100)),
                ('liqueur', models.CharField(default='no liqueur', max_length=100)),
                ('juice', models.CharField(default='no juice', max_length=100)),
                ('garnish', models.CharField(default='no garnish', max_length=100)),
                ('citrus', models.CharField(default='no citrus', max_length=100)),
                ('soda', models.CharField(default='no soda', max_length=100)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(default='images/drank.jpg', upload_to='images/')),
            ],
        ),
    ]
